/**
 * Inventory Domain Types
 * ======================
 * This file defines all **TypeScript interfaces** used throughout the system.
 *
 * Responsibilities:
 * - Describe the shape of inventory-related data
 * - Act as contracts between layers (CLI ↔ Service ↔ Repository)
 * - Improve type safety and readability
 *
 * This file represents the **Domain Model Layer**.
 *
 * This file MUST:
 * - Contain only type/interface definitions
 * - Be free of logic or side effects
 *
 * This file MUST NOT:
 * - Contain functions
 * - Access the database
 * - Perform validation
 */

/* -------------------------------------------------------------------------- */
/*                              Core Entity Type                               */
/* -------------------------------------------------------------------------- */

/**
 * InventoryItem
 *
 * Represents a **full inventory record** as stored in the database.
 *
 * Used by:
 * - Repository layer (full entity reads)
 * - Service layer (business logic)
 *
 * Includes:
 * - Metadata fields (createdAt, updatedAt)
 */
export interface InventoryItem {
  /** Unique identifier for the inventory item */
  itemId: number;

  /** Display name of the item */
  name: string;

  /** Category the item belongs to */
  category: string;

  /** Quantity available */
  quantity: number;

  /** Optional storage location */
  location?: string;

  /** Timestamp when the item was created */
  createdAt: Date;

  /** Timestamp when the item was last updated (if any) */
  updatedAt?: Date;
}

/* -------------------------------------------------------------------------- */
/*                             Create / Update Types                           */
/* -------------------------------------------------------------------------- */

/**
 * CreateInventoryItem
 *
 * Represents the data required to **create a new inventory item**.
 *
 * Used by:
 * - CLI (Add Inventory Item)
 * - Service layer (validation)
 * - Repository layer (INSERT operations)
 *
 * Note:
 * - Does NOT include itemId or timestamps
 * - These are generated by the database
 */
export interface CreateInventoryItem {
  /** Item name */
  name: string;

  /** Item category */
  category: string;

  /** Initial quantity */
  quantity: number;

  /** Optional location */
  location?: string;
}

/**
 * UpdateInventoryItem
 *
 * Represents **partial updates** to an inventory item.
 *
 * Used by:
 * - CLI (Update Inventory Item)
 * - Service layer (update validation)
 *
 * Notes:
 * - All fields are optional
 * - Only provided fields will be updated
 */
export interface UpdateInventoryItem {
  name?: string;
  category?: string;
  quantity?: number;
  location?: string;
}

/* -------------------------------------------------------------------------- */
/*                              View / Output Types                            */
/* -------------------------------------------------------------------------- */

/**
 * InventoryViewItem
 *
 * Represents a **read-only, display-friendly** version of an inventory item.
 *
 * Used by:
 * - View Inventory
 * - Filter / Search Inventory
 * - JSON export
 *
 * Excludes:
 * - createdAt
 * - updatedAt
 *
 * Purpose:
 * - Prevents leaking internal metadata to the UI
 */
export interface InventoryViewItem {
  /** Inventory item ID */
  itemId: number;

  /** Item name */
  name: string;

  /** Item category */
  category: string;

  /** Quantity available */
  quantity: number;

  /** Optional location */
  location?: string;
}

/* -------------------------------------------------------------------------- */
/*                               Filter Criteria                               */
/* -------------------------------------------------------------------------- */

/**
 * InventoryFilter
 *
 * Represents optional filter criteria for searching inventory items.
 *
 * Used by:
 * - Filter / Search Inventory feature
 * - Service and Repository layers
 *
 * Behavior:
 * - All fields are optional
 * - Filters are combined using AND logic
 */
export interface InventoryFilter {
  /** Partial name match */
  name?: string;

  /** Exact category match */
  category?: string;

  /** Exact location match */
  location?: string;

  /** Minimum quantity (inclusive) */
  minQuantity?: number;

  /** Maximum quantity (inclusive) */
  maxQuantity?: number;
}
